/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package list;

import java.util.ArrayList;
import java.util.List;
import java.util.Iterator;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        List<String> list = new ArrayList<>();

        list.add("李四");
        list.add("张三");
        list.add("李四");
        list.add("王五");
        list.add("赵六");

        System.out.println(list);

        // 方法1：迭代器遍历
        Iterator<String> iterator = list.iterator();

        while (iterator.hasNext()) {
            String s = iterator.next();

            if ("李四".equals(s)) {
                iterator.remove();
            }
        }

        System.out.println("第1次删除后：" + list);
    }
}
